name: Deploy static build

on:
  push:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Deps and Build Storybook
        run: npm install && npm run build-storybook
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./storybook-static
          branch: gh-pages
          target-folder: docs/docs
          clean-exclude: pr-preview