name: Storybook PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use node.js 14.15
        uses: actions/setup-node@v1
        with:
          node-version: 14.15
      - name: Install Deps and Build SB Preview
        run: npm install && npm run build-storybook
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./storybook-static/
          preview-branch: gh-pages
          umbrella-dir: docs/pr-preview
          action: auto
